platform :ios, '9.3'

target 'Event App' do
  use_frameworks!
  pod 'SwiftLint'
  pod 'XLPagerTabStrip', '~> 9.0'
  pod 'Reusable'
  pod 'Cosmos', '~> 21.0'
  pod 'ExpandableLabel'
  target 'Event AppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Event AppUITests' do
    # Pods for testing
  end

end
